### ISSUE TITLE
Frozen hard requirements in setup.py break everything

### ISSUE THREAD

**Issue by awilfox** [hynek/doc2dash#45]
``pip`` is more than happy to write six 1.7.3 to ~/.local, even though it *requires* 1.10.0, because doc2dash's setup.py specifies == 1.7.3 (though I see that has been bumped to 1.9.0 since the last PyPI update).  This resulted in my inability to run pip, and most other Python utilities on my system that require six (until I used ``python -s -m pip install -U --user --force-reinstall six`` to force an update).

Is there any way to possibly be a bit more lax in version requirements?  doc2dash 2.0.2 seems perfectly happy using six 1.10.0.

**Comment by hynek** [comment]
Don’t install Python applications into your global site-packages.  It will break your Python installation sooner or later: https://hynek.me/articles/virtualenv-lives/

The requirements are strict because it’s not possible to anticipate how future releases of dependencies will behave and the bug tracker would be full of reports from people with broken installations.

I recommend using [pipsi](https://github.com/mitsuhiko/pipsi).
